/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IDIDRegistry__factory } from "./IDIDRegistry__factory";
export { IDIDStorage__factory } from "./IDIDStorage__factory";
