/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { DIDRegistry__factory } from "./DIDRegistry__factory";
export { DIDStorage__factory } from "./DIDStorage__factory";
