import { SEOConfig } from '../types/seo';

const baseUrl = process.env.NODE_ENV === 'production' 
  ? 'https://safepsy.com' 
  : 'http://localhost:5173';

const defaultImage = `${baseUrl}/Logotransparent.png`;

export const seoConfig: Record<string, SEOConfig> = {
  '/': {
    title: 'SafePsy - Privacy-First Online Therapy Platform',
    description: 'Revolutionizing online therapy with privacy-first technology. Secure, ethical, and human-centered mental health support using blockchain and digital identity.',
    keywords: 'online therapy, mental health, privacy, blockchain, digital identity, counseling, secure therapy, ethical therapy, privacy-first',
    ogTitle: 'SafePsy - Privacy-First Online Therapy Platform',
    ogDescription: 'Revolutionizing online therapy with privacy-first technology. Secure, ethical, and human-centered mental health support.',
    ogImage: defaultImage,
    ogUrl: baseUrl,
    twitterTitle: 'SafePsy - Privacy-First Online Therapy',
    twitterDescription: 'Revolutionizing online therapy with privacy-first technology. Secure, ethical, and human-centered mental health support.',
    twitterImage: defaultImage,
    twitterCard: 'summary_large_image',
    canonical: baseUrl,
  },
  '/about-us': {
    title: 'About Us - SafePsy | Privacy-First Mental Health Platform',
    description: 'Learn about SafePsy\'s mission to revolutionize mental health care with privacy-first technology. Meet our team and discover our commitment to ethical, secure therapy.',
    keywords: 'about SafePsy, mental health team, privacy-first therapy, ethical therapy, secure counseling, mental health mission',
    ogTitle: 'About SafePsy - Privacy-First Mental Health Platform',
    ogDescription: 'Learn about SafePsy\'s mission to revolutionize mental health care with privacy-first technology.',
    ogImage: defaultImage,
    ogUrl: `${baseUrl}/about-us`,
    twitterTitle: 'About SafePsy - Privacy-First Mental Health',
    twitterDescription: 'Learn about SafePsy\'s mission to revolutionize mental health care with privacy-first technology.',
    twitterImage: defaultImage,
    twitterCard: 'summary_large_image',
    canonical: `${baseUrl}/about-us`,
  },
  '/sap-policy': {
    title: 'Security & Privacy Policy - SafePsy',
    description: 'Comprehensive security and privacy policy for SafePsy. Learn how we protect your mental health data with blockchain technology and privacy-by-design principles.',
    keywords: 'privacy policy, security policy, data protection, GDPR, mental health privacy, blockchain security, privacy by design',
    ogTitle: 'Security & Privacy Policy - SafePsy',
    ogDescription: 'Comprehensive security and privacy policy for SafePsy. Learn how we protect your mental health data.',
    ogImage: defaultImage,
    ogUrl: `${baseUrl}/sap-policy`,
    twitterTitle: 'Security & Privacy Policy - SafePsy',
    twitterDescription: 'Comprehensive security and privacy policy for SafePsy. Learn how we protect your mental health data.',
    twitterImage: defaultImage,
    twitterCard: 'summary',
    canonical: `${baseUrl}/sap-policy`,
  },
  '/contact-us': {
    title: 'Contact Us - SafePsy | Get in Touch',
    description: 'Contact SafePsy for support, partnerships, or questions about our privacy-first mental health platform. We\'re here to help with your mental health journey.',
    keywords: 'contact SafePsy, mental health support, therapy questions, partnership, customer support, mental health help',
    ogTitle: 'Contact SafePsy - Get in Touch',
    ogDescription: 'Contact SafePsy for support, partnerships, or questions about our privacy-first mental health platform.',
    ogImage: defaultImage,
    ogUrl: `${baseUrl}/contact-us`,
    twitterTitle: 'Contact SafePsy - Get in Touch',
    twitterDescription: 'Contact SafePsy for support, partnerships, or questions about our privacy-first mental health platform.',
    twitterImage: defaultImage,
    twitterCard: 'summary',
    canonical: `${baseUrl}/contact-us`,
  },
  '/join-our-waitlist': {
    title: 'Join Our Waitlist - SafePsy | Early Access',
    description: 'Join SafePsy\'s waitlist for early access to our privacy-first mental health platform. Be among the first to experience secure, ethical online therapy.',
    keywords: 'SafePsy waitlist, early access, mental health platform, privacy-first therapy, secure counseling, therapy waitlist',
    ogTitle: 'Join SafePsy Waitlist - Early Access',
    ogDescription: 'Join SafePsy\'s waitlist for early access to our privacy-first mental health platform.',
    ogImage: defaultImage,
    ogUrl: `${baseUrl}/join-our-waitlist`,
    twitterTitle: 'Join SafePsy Waitlist - Early Access',
    twitterDescription: 'Join SafePsy\'s waitlist for early access to our privacy-first mental health platform.',
    twitterImage: defaultImage,
    twitterCard: 'summary_large_image',
    canonical: `${baseUrl}/join-our-waitlist`,
  },
};
